CREATE TABLE IF NOT EXISTS stats (
     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     app VARCHAR(20) NOT NULL,
     uri VARCHAR(30) NOT NULL,
     ip VARCHAR(20) NOT NULL,
     timest TIMESTAMP WITHOUT TIME ZONE NOT NULL
);